# Allow coverage to decrease by 0.05%.
coverage:
  status:
    project:
      default:
        threshold: 0.05%

# Don't post a comment on pull requests.
comment: off

codecov:
  branch: Develop
  require_ci_to_pass: false

ignore:
  - "*/tests/*"
