dataset: cifar10
seed: 60
search_space: nasbench201
out_dir: /work/dlclarge2/agnihotr-ml/NASLib/naslib/optimizers/oneshot/gsparsity/run/augmix/
optimizer: darts_aug

search:

  #GSparsity
  grad_clip: 5
  threshold: 0.000001
  weight_decay: 120
  learning_rate: 0.01
  momentum: 0.8
  normalization: div
  normalization_exponent: 0.5
  batch_size: 64
  learning_rate_min: 0.0001
  epochs: 50
  warm_start_epochs: 0
  train_portion: 0.7
  data_size: 35000

  #additional params
  unrolled: False
  arch_learning_rate: 0.0003
  arch_weight_decay: 0.001
  output_weights: True
  fidelity: -1
  checkpoint_freq: 30

  # GDAS
  tau_max: 10
  tau_min: 0.1

  # RE
  sample_size: 10
  population_size: 30
  
  # LS
  num_init: 10
  
  # BANANAS
  k: 10
  num_ensemble: 3
  acq_fn_type: its
  acq_fn_optimization: mutation
  encoding_type: path
  num_arches_to_mutate: 2
  max_mutations: 1
  num_candidates: 100
  
  # BP
  predictor_type: oneshot
  debug_predictor: False

  #augmix arguments:
  cutout: False
  augmix: True
  alpha: 1.0 #weigthing cross-entropy loss and augmix loss for the final loss *12
  all_ops: True
  mixture_width: 3
  mixture_depth: -1
  aug_severity: 3
  no_jsd: False
  aug_architecture: True
  aug_operations: True
  base_path: /work/dlclarge2/agnihotr-ml/NASLib/naslib/data/augmix/
  cutout_length: 16
  cutout_prob: 1.0
  drop_path_prob: 0.2
  auxiliary_weight: 0.4

evaluation:
  checkpoint_freq: 30
  batch_size: 64
  learning_rate: 0.025
  learning_rate_min: 0.00
  momentum: 0.9
  weight_decay: 0.0003
  epochs: 600
  warm_start_epochs: 0
  grad_clip: 5
  train_portion: 1.
  data_size: 50000

  cutout: False
  cutout_length: 16
  cutout_prob: 1.0
  drop_path_prob: 0.2
  auxiliary_weight: 0.4

  #augmix arguments:
  augmix: False
  aug_alpha: 1.0 #weigthing cross-entropy loss and augmix loss for the final loss *12
  all_ops: True
  mixture_width: 3
  mixture_depth: -1
  aug_severity: 3
  no_jsd: False
  base_path: /work/dlclarge2/agnihotr-ml/NASLib/naslib/data/augmix/
